package com.redhat.demo.crv;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceNowMessage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Level")
   private java.lang.Integer level;
   private java.lang.String description;

   public ServiceNowMessage()
   {
   }

   public java.lang.Integer getLevel()
   {
      return this.level;
   }

   public void setLevel(java.lang.Integer level)
   {
      this.level = level;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public ServiceNowMessage(java.lang.Integer level,
         java.lang.String description)
   {
      this.level = level;
      this.description = description;
   }

}