package com.redhat.demo.crv;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VirusTotalLookupMessage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String filename;
   private java.lang.String fileId;
   private java.lang.String metadata;

   public VirusTotalLookupMessage()
   {
   }

   public java.lang.String getFilename()
   {
      return this.filename;
   }

   public void setFilename(java.lang.String filename)
   {
      this.filename = filename;
   }

   public java.lang.String getFileId()
   {
      return this.fileId;
   }

   public void setFileId(java.lang.String fileId)
   {
      this.fileId = fileId;
   }

   public java.lang.String getMetadata()
   {
      return this.metadata;
   }

   public void setMetadata(java.lang.String metadata)
   {
      this.metadata = metadata;
   }

   public VirusTotalLookupMessage(java.lang.String filename,
         java.lang.String fileId, java.lang.String metadata)
   {
      this.filename = filename;
      this.fileId = fileId;
      this.metadata = metadata;
   }

}